var mongoose = require('mongoose');
var moment   = require('moment');

var Schema = mongoose.Schema;

var jobDetailSchema = new Schema({
	Production_Batch                     : {type: String, default: null},
	Print_Batch                          : {type: String, default: null},
	Client_Name                          : {type: String, default: null},
	Client_Address                       : {type: String, default: null},
	Double_Dispensing_Indicator          : {type: String, default: null},
	Date_Dispensed                       : {type: String, default: null},
	Script_Number	                     : {type: String, default: null},
	Item_Count                           : {type: String, default: null},
	Drug_Description                     : {type: String, default: null},
	Dosage_Line_1                        : {type: String, default: null},
	Dosage_Line_2                        : {type: String, default: null},
	Dosage_Line_3                        : {type: String, default: null},
	Dosage_Line_4                        : {type: String, default: null},
	Title	                             : {type: String, default: null},
	Initials                             : {type: String, default: null},
	Surname	                             : {type: String, default: null},
	Pharmacist                           : {type: String, default: null},
	File_No                              : {type: String, default: null},
	Batch	                             : {type: String, default: null},
	Expiry                               : {type: String, default: null},
	Lane	                             : {type: String, default: null},
	FCY	                                 : {type: String, default: null},
	SQ	                                 : {type: String, default: null},
	Order_No                             : {type: String, default: null},
	Line_No	                             : {type: String, default: null},
	Hospital_Ref                         : {type: String, default: null},
	Production_Batch_1                   : {type: String, default: null},
	Production_Batch_2                   : {type: String, default: null},
	Production_Expiry                    : {type: String, default: null},
	Name	                             : {type: String, default: null},
	Fridge                               : {type: String, default: null},
	SSEQ                                 : {type: String, default: null},
	Date_Of_Birth                        : {type: String, default: null},
	Cell_No	                             : {type: String, default: null},
	ID_Number                            : {type: String, default: null},
	Collection_Date                      : {type: String, default: null},
	Next_Collection_Date                 : {type: String, default: null},
	Collection_Point                     : {type: String, default: null},
	Profile_No	                         : {type: String, default: null},
	Repeat	                             : {type: String, default: null},
	Repeat_Notice	                     : {type: String, default: null},
	Following_Items_Not_Included	     : {type: String, default: null},
	Line_1                               : {type: String, default: null},
	Line_2                               : {type: String, default: null},
	Line_3                               : {type: String, default: null},
	Line_4                               : {type: String, default: null},
	Facility_Review                      : {type: String, default: null},
	Parcel_Ref                           : {type: String, default: null},
	Collection_Point_Ref                 : {type: String, default: null},
	MpNo                                 : {type: String, default: null},
	Hub                                  : {type: String, default: null},
	Zone                                 : {type: String, default: null},
	Second_Rx_Ref                        : {type: String, default: null},
	Parcel_Reference_Number              : {type: String, default: null},
	MAN_SEQ                              : {type: String, default: null},
	SEQUENCE                             : {type: String, default: null},
	created_at                           : {type: String, default: moment(new Date()).format('YYYY-MM-DD')},
	updated_at                           : {type: String, default: moment(new Date()).format('YYYY-MM-DD')}

}, { collection: 'JobDetail'})

module.exports = mongoose.model('JobDetail', jobDetailSchema);